// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"net/url"
)

func VideoCompare(inputFile, tempFile string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"videoSplitCompare\" class=\"relative w-full my-6 select-none\" @mousemove.window=\"onDrag($event)\" @mouseup.window=\"onDragEnd()\" @touchmove.window=\"onDrag($event)\" @touchend.window=\"onDragEnd()\"><!-- Labels --><div class=\"flex flex-row justify-between mb-2 px-2\"><div class=\"text-sm font-semibold text-muted-foreground\">Original</div><div class=\"text-sm font-semibold text-muted-foreground\">Transcoded</div></div><!-- Comparison container --><div x-ref=\"container\" class=\"relative w-full overflow-hidden rounded border border-border bg-black\" style=\"aspect-ratio: 16/9;\"><!-- Background: Original video (full width) --><video x-ref=\"videoA\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(templ.URL("/media/?path=" + url.QueryEscape(inputFile)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/elements/videocompare.templ`, Line: 30, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" preload=\"metadata\" class=\"absolute inset-0 w-full h-full object-contain\" @play=\"onPlay($refs.videoA)\" @pause=\"onPause($refs.videoA)\" @seeking=\"onSeek($refs.videoA)\" @seeked=\"onSeeked($refs.videoA)\"></video><!-- Foreground: Transcoded video (clipped) --><video x-ref=\"videoB\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.URL("/media/?path=" + url.QueryEscape(tempFile)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/elements/videocompare.templ`, Line: 42, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" preload=\"metadata\" class=\"absolute inset-0 w-full h-full object-contain\" :style=\"'clip-path: inset(0 0 0 ' + position + '%)'\" @play=\"onPlay($refs.videoB)\" @pause=\"onPause($refs.videoB)\" @seeking=\"onSeek($refs.videoB)\" @seeked=\"onSeeked($refs.videoB)\"></video><!-- Draggable handle --><div x-ref=\"handle\" class=\"absolute top-0 bottom-0 w-1 bg-white shadow-lg cursor-ew-resize z-10\" :style=\"'left: ' + position + '%'\" @mousedown.prevent=\"onDragStart()\" @touchstart.prevent=\"onDragStart()\"><!-- Handle grip circle --><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 bg-white rounded-full shadow-md flex items-center justify-center\"><svg class=\"w-4 h-4 text-gray-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-width=\"2\" d=\"M8 8l-4 4 4 4M16 8l4 4-4 4\"></path></svg></div></div></div><!-- Playback controls --><div class=\"flex justify-center gap-2 mt-3\"><button type=\"button\" class=\"px-3 py-1 text-sm border rounded hover:bg-accent\" @click=\"$refs.videoA.paused ? $refs.videoA.play() : $refs.videoA.pause()\"><span x-text=\"$refs.videoA && $refs.videoA.paused ? '▶ Play' : '⏸ Pause'\"></span></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
